[versions]
agp = "8.13.2"
androidxActivity = "1.12.2"
androidxAppCompat = "1.7.1"
androidxCompose = "1.10.0"
androidxComposeMaterial3 = "1.4.0"
androidxCore = "1.17.0"
androidxCoreSplashscreen = "1.2.0"
androidxDataStore = "1.2.0"
androidxDocumentFile = "1.1.0"
androidxLifecycle = "2.10.0"
androidxNavigation = "2.9.6"
androidxRoom = "2.8.4"
cashLicensee = "1.14.1"
koin = "4.1.1"
kotlin = "2.3.0"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1-0.6.x-compat"
kotlinxSerialization = "1.9.0"
ksp = "2.3.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
